### ISSUE TITLE
Duplicates on web site

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#1004]
Looks like this is a persistent issue on https://open-source-ios-apps.netlify.app

Example
https://open-source-ios-apps.netlify.app/category/browser/
<img width="1188" alt="Screen Shot 2021-12-06 at 9 05 49 AM" src="https://user-images.githubusercontent.com/4723115/144889963-3bbb9798-c4b3-4408-a855-8930ae801901.png">

@chmac

**Comment by chmac** [comment]
@dkhamsing Super weird. I was never able to reproduce this locally. It seems to be related to the netlify caching behaviour somehow. I read [this blog post from netlify](https://www.netlify.com/blog/2020/06/11/5-optimizations-for-faster-gatsby-builds/) about caching. They talk about a [Gatsby cache plugin](http://app.netlify.com/plugins/netlify-plugin-gatsby-cache/install) which is installed via the netlify dashboard. It's a netlify "plugin" rather than a Gatsby plugin. Is that enabled on the site? If not, could be worth trying that to see if it makes any progress.

As I can't reproduce this issue, I also can't really debug it. If I had access to the Netlify account while it was in the broken state, I could investigate. I think that netlify gives you a way to re-run a build with an SSH server so you can login and see what's going on. Then we'd be able to see where the duplicates are on the filesystem and maybe figure out what's causing it, or at least find a workaround.

**Comment by dkhamsing** [comment]
@chmac For the Gatsby cache plugin https://app.netlify.com/teams/dkhamsing/plugins/netlify-plugin-gatsby-cache/install .. it says 

> This plugin is deprecated. Please install the Essential Gatsby plugin instead

I've installed the Essential Gatsby plugin 🙏

**Comment by chmac** [comment]
@dkhamsing Okay, sounds good. Now we wait! Hopefully that clears up the issue, but we'll have to wait and see I think.

I know a bit about the architecture of Gatsby and I can't figure out where the duplicates could be coming from. We source all the data from the git repo. But maybe netlify is doing some unexpected or weird caching and that plugin will sort it out. Fingers crossed!

**Comment by dkhamsing** [comment]
@chmac 
hm no change 😢 let me know if you want to try the ssh thing

**Comment by chmac** [comment]
@dkhamsing I'm certainly happy to try it. But I'm not sure how to do that. I don't know if you can add me to your netlify account without paying for a team plan. I guess your login on netlify is via your GitHub account? I tried making my own netlify build to see if I could reproduce the issue there but that never worked.

Any idea how I can get access to your netlify build?

**Comment by dkhamsing** [comment]
I do sign in Netlify with my GitHub account. It is not clear if adding a team member cost money or not 🤔

**Comment by chmac** [comment]
@dkhamsing OK, let me know if you figure out a way to get me access.

**Comment by dkhamsing** [comment]
@chmac hey considering disabling netlify

**Comment by chmac** [comment]
@dkhamsing There are definitely other ways to manage the build. Unfortunately the domain is owned by netlify. But we could deploy a redirect to that domain and use a GitHub pages site instead. GitHub also has some build process / CI type stuff now. But one could also run a job elsewhere to do the build and push to GitHub.

Not sure what sort of resources you have. As an example, if you have a server that has your GitHub ssh key available all the time, you could run a simple cron job to update the build once a day and do a push to GitHub.

It's a super weird problem.

Oh, what about asking netlify support? They have, at least in the past, been pretty good about this kind of thing. Maybe they'll investigate and figure out what the issue is. Could be useful for their gatsby support...
