### ISSUE TITLE
Write iOS app

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#334]
#333 
😉

**Comment by matteocrippa** [comment]
@dkhamsing imho if you switch only the URI at line 19 of https://github.com/matteocrippa/awesomeSwift-iOS-App/blob/master/appname/AwesomeSwiftAPI.swift it should work already fine

**Comment by dkhamsing** [comment]
Thx!

**Comment by michieriffic** [comment]
@dkhamsing do you still need help on this? :)

**Comment by dkhamsing** [comment]
sure!

**Comment by michieriffic** [comment]
Ok, let me think of the design. Btw, what should the app name be? Open Source iOS Apps? 
The only thing that I can see that can be a hindrance for approval if it looks like an App Store. Lol :)

**Comment by matteocrippa** [comment]
pretty hard they approve an app w/ iOS in the name at the first time, you will manage to find a good reviewer in order to have it approved.

**Comment by dkhamsing** [comment]
yeah if that doesn't work just go with "Open Source Apps"

**Comment by matteocrippa** [comment]
or you can try to do something iOSA (iOS Open Source Apps)

**Comment by michieriffic** [comment]
@matteocrippa ikr! Any name suggestion? Btw, cool name for the "Awesome Swift". 

@dkhamsing we just have to make sure, we don't look or act like an App Store. They don't approve that. :)

**Comment by michieriffic** [comment]
@dkhamsing - what are the other possible attributes that can be listed to tags?
 
tags: List of app attribute tags, use swift if the app is written in Swift

**Comment by matteocrippa** [comment]
you can use this as data model

```
 {
      "title": "UitzendingGemist by jeffkreeftmeijer",
      "category": "apple-tv",
      "description": "Dutch Public Broadcasting video on demand",
      "source": "https://github.com/jeffkreeftmeijer/UitzendingGemist",
      "license": "mit",
      "tags": [
        "swift"
      ],
      "stars": 63
    },
```

I think that the only tags atm is  swift

**Comment by scribblemaniac** [comment]
@michieriffic There are two tags at the moment, `swift` and `archive` (both as strings). If you need help understanding the structure, check out the [schema.json](https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/schema.json), it has all of the currently supported tags and a brief description for all of them.

@dkhamsing I've noticed there were quite a few notifications from this project lately, sorry I haven't been able to help but I am currently traveling so I can't really work on this stuff much. Congrats on breaking 500 apps!! :cake:

**Comment by michieriffic** [comment]
@scribblemaniac thanks. What does 'archive' mean as a tag? thanks. :)

**Comment by dkhamsing** [comment]
Archive means not shown on the main list - deleted, no longer maintained..

**Comment by dkhamsing** [comment]
@scribblemaniac no worries

**Comment by scribblemaniac** [comment]
@michieriffic Apps with the archive tag no longer build. Instead of being put in the main README.md, they are put in ARCHIVE.md. For the app, it could in my opinion be put in a separate section, grayed out, or just ignored entirely.

**Comment by matteocrippa** [comment]
@dkhamsing what do you think to improve the AwesomeSwift app in order to get data from both the two JSON, we already share format so we can easily reach that goal with a sort of swiss army knife app for devs.

@michieriffic if you want you can have a look at this already existing (and open sourced) app that we use in [AwesomeSwift](https://github.com/matteocrippa/awesome-swift) - https://github.com/matteocrippa/awesomeSwift-iOS-App

**Comment by dkhamsing** [comment]
Forking or using @matteocrippa's app could be a starting point

**Comment by matteocrippa** [comment]
or we can create a branch on that proj

**Comment by michieriffic** [comment]
@dkhamsing I think what @matteocrippa is suggesting is to combine both Awesome Swift and Open Source iOS as one app as it complements each other. Am I correct? 

Actually, I have thought of this last night and saw a lot of Awesome List available which can be combined in one app. 

Because the new Apple Guidelines is suggesting that if you're just making the same app and just changing its content, it's better to create one app. 

> Apple Review Guidelines 4.3 
> Don’t create multiple Bundle IDs of the same app. If your app has different versions for specific locations, sports teams, universities, etc., consider submitting a single app and provide the variations using in-app purchase. 

The only thing about Awesome is that the list should be curated, while open source iOS is pulling all the possible open source iOS app available. 

Overall, I've research possible design styles that would best suit the app. :)

**Comment by dkhamsing** [comment]
combine or fork / create different app is fine by me, end goal is to have an app :-)

**Comment by matteocrippa** [comment]
I was only wondering that combining would be faster, we have only to find a name that fits back both the two lists and polish a little features keeping the repo public

**Comment by dkhamsing** [comment]
Yes seems that would be faster

**Comment by dkhamsing** [comment]
closed by mistake 😅

**Comment by michieriffic** [comment]
@matteocrippa i'll try to make a version of my app first and see what I can integrate in from your app. I've seen your repo and you are using LeeGo for the UI and I prefer using the storyboard or doing the UI using Apple's Framework. :) 

@dkhamsing are you ok with that? :)

**Comment by dkhamsing** [comment]
Yeah it's fine 
Thank you!

**Comment by matteocrippa** [comment]
@michieriffic if you can wait a couple of days I'll push a new version of the app in a separate branch that strip off the POC of LeeGo, making use of Storyboard and XIBs for max reusability and faster UI development.
If you want in the meanwhile feel free to share a mockup of the idea so we can work in order to review that first and figure out how to implement.

**Comment by matteocrippa** [comment]
@michieriffic if you want have a look at this https://github.com/matteocrippa/awesomeSwift-iOS-App/tree/feature/newUI I pushed an early setup, if you want have a look at CreditsViewController to figure out how to approach.

In order to avoid merge issues, I strongly suggest to keep the storyboard as simple as possibile, but make use of XIBs

**Comment by matteocrippa** [comment]
I'd suggest to move the discussion over there: https://github.com/matteocrippa/awesomeSwift-iOS-App

Let's assume to use the new branch under **feature/newUI**

I pushed some improvements and the new XIB based approach, feel free to use issues over there to continue

**Comment by dkhamsing** [comment]
Got a simple app up 😄

**Comment by matteocrippa** [comment]
yep, I was waiting for mockup in order to avoid to go too far in app development and then have to switch back

**Comment by dkhamsing** [comment]
cool

**Comment by michieriffic** [comment]
Cool! 👍 @matteocrippa I'll be sending the mockup now. I've use the same color palette as your previous app.
