### ISSUE TITLE
Separate Apps available on App Store  

### ISSUE THREAD

**Issue by wangkesen** [dkhamsing/open-source-ios-apps#490]
Is it possible to separate apps available on the App Store for users to download/purchase versus just having them all mixed together? 
Obviously this is a great list either way but I feel it would be much better viewed if Apps that are actually available on the store were separate. A lot of users would be browsing for Apps that they can actually just download and use immediately on their devices rather then code they they have to implement in another way.

**Comment by dkhamsing** [comment]
this is something i had planned actually since the readme is generated

should be pretty easy

all the data is from `contents.json` which currently generates
- README.md
- ARCHIVE.md

the plan is to create another file, maybe called APPSTORE.md which would only have apps available to download

will try to work on this :)

**Comment by wangkesen** [comment]
Great, that sounds awesome! Sorry I would offer to help in some way but I’m new to Github and I’m not great even at markdown yet haha. Thanks for this by the way, it’s awesome to have this list. Beforehand I would just be querying the App Store getting the same results. Appreciate your work!

**Comment by dkhamsing** [comment]
@wangkesen look for APPSTORE.md https://github.com/dkhamsing/open-source-ios-apps/blob/master/APPSTORE.md

**Comment by wangkesen** [comment]
Awesome! Thanks so much to! This is wicked :)
