### ISSUE TITLE
Contribute items to Alternativeto.net

### ISSUE THREAD

**Issue by sirjamesgray** [dkhamsing/open-source-ios-apps#567]
Not to divert engagement away from this repo, but I feel like it would be much more useful to people seeking open source projects to contribute some of these projects to Alternativeto.net so people can find projects while looking for alternatives to specific software.

**Comment by dkhamsing** [comment]
Closing for now, pls reopen if there is more interest

**Comment by scribblemaniac** [comment]
@sirjamesgray Don't get me wrong, I like AlternativeTo a lot, I use it often and have contributed to it before, but there are numerous reasons why it's not a replacement for this project:
- Differing purposes. The goal of AlternativeTo is obviously to show you alternatives to existing software, while the purpose of OSIA (imho) is to introduce people to new iOS apps that follow the open source paradigm. Both projects can be used for the other purpose, but that is not what they were designed for and they do not do that as well as the project that is dedicated to that purpose.
- Transparency. One of the major issue I have with AlternativeTo is the lack of transparency. Being run by a private corporation with propriety server software means that they don't have to show how they operate, or justify any of their actions. Their terms of service say that they can remove any entries without needing to provide any reason. While it's true that we can do that as well, it is immediately and permanently visible to everyone that we have done so, and if someone has an issue with that, they can of course fork our repository and create a "better" list that includes/excludes entries as that particular person desires. I'm not saying that AlternativeTo does anything unfairly, just that they can do so and not receive any meaningful consequences or even without anyone knowing. It's not too far fetched to imagine them adding some "likes"  to companies that pass a little money under the table.
- Data availability. One of the things that makes OSIA great, even when compared with other open lists such as many of the Awesome lists is that it provides all of the information in both an easily human-readable format, and a machine-parasble JSON format. This allows anyone to easily integrate the data from our project into their own projects. For example, you could use it to create a website, to populate a package manager for iOS, or other uses beyond what us developers could envision. AlternativeTo on the other hand only provides the people-oriented user interface. They had an API, but from the looks like they took it down years ago and have no intention of ever re-enabling it.
- Advertisements. Advertisements are annoying. AlternativeTo has advertisements, and I don't fault them for that because bandwidth doesn't grow on trees, but it is another differentiating factor between us and them. We do not have any advertisements on our README or on our semi-official website, so no third-party companies (with the unavoidable exception of GitHub, and maybe some CDNs) have access to your browsing data. For the security conscious, or those who simply do not like being sold things while looking for open software, OSIA is clearly superior.

There is quite a bit of work that can still be done to improve this project, and there are many benefits to promoting this independent initiative over other similar sites such as AlternativeTo which hopefully you can start to appreciate now.
