### ISSUE TITLE
Sponsorship 

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#568]
How does the community feel about a company sponsoring this project? What should we do with the money? It would be a couple of hundreds of dollars 

cc @vpeschenkov @scribblemaniac

**Comment by scribblemaniac** [comment]
I'm not against the idea. What would we be doing for them in return, adding a logo to the readme or something along those lines? As long as it's not anything intrusive, like embedded advertisements, or higher positions on the list without clear indication that it is sponsored, then I am in favor of accepting such a proposal. Even if we don't need the money now, it could useful to save it for some future venture.

Off the top of my head, there are two ideas for what we could use the money for right now. First is purchasing a domain name for our website. osia.cc is pretty cheap ($13/year), and cc is sometimes used by open source projects like Arduino (backronym for Creative Commons supposedly). osia.io is pricier ($42/year) but is used more often by tech companies. Google treats cc and io as generic TLDs which is good. If you want something longer like opensourceiosapps, then your choice of TLDs is much greater and you can get even the standard ones quite cheap (org, com, and net are all available for <$17/year). I recommend namecheap if you want to look up more options.

My second idea is something I've been thinking of doing on my own for a while now. Maybe this is reaching too far beyond our current goals for OSIA, I'll let you guys be the judge. In my eyes, three of the purposes of OSIA are: 1. Provide a platform for developers to gain greater exposure for their open source apps. 2. Provide a moderate trust guarantee for applications (we obviously would take any reports of malicious applications on our list very seriously). 3.  Promote the usage of open source apps among the general population of iOS users. However there is a significant roadblock to the last point. If you look at our list, you will see that the majority of these apps are not available on the official App Store, so unless the users are experienced at compiling and deploying open source applications, these entries are all out of reach for them. My idea addresses this and also simultaneously promotes the other two aforementioned goals. What we could do is use the money to purchase an organization-level Apple Developer Program membership ($99/year). We could then use this membership to make some applications from our list available on the App Store. This provides a great service to open source apps, which often can't afford the membership. It obviously helps users who can't install apps on their own. Finally it helps promote trust because an independent and somewhat trustworthy organization is uploading the app rather than the rip-off clone apps from random people you sometimes see when looking for versions of these apps on the app store. We should probably only upload apps with the explicit consent or at the request of the developer (for many licenses this isn't technically necessary, but we would want to avoid any potential legal issues). We could then also provide the option to made the app cost money if developer wants, and we would forward the profits to the developer to support the continued development of the app while taking a small standardized percentage to help cover Apple membership and app store/list maintenance costs. Additional revenue could come from sponsorships like this or donations (I think many developers would be willing to donate if we could save them the cost of an the developer membership). Yes this proposal would add more work for us, but we already do lots of the stuff necessary for app submission: gathering descriptions, links, and screenshots, obviously we already have the source code, and you build the apps anyway to get screenshots and to look for archivable entries. Most of the overhead added by this would be organizational and I will absolutely help out where I can if everyone else is on board with this.

**Comment by dkhamsing** [comment]
Some interesting ideas, thanks for writing. The ad would be a message towards the top of the readme: sponsored by company name + a blurb about their product. The last idea is very ambitious!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Well I will contact the sponsor and agree to run the ad. Hope we can come up with what to do afterwards. Thx !

**Comment by dkhamsing** [comment]
It’s taking a while but we may starting the sponsorship soon
Keep u posted

**Comment by dkhamsing** [comment]
We received a whooping $242.45 from https://instabug.com, working on the copy to be added

**Comment by dkhamsing** [comment]
Sponsorship is in progress, on for a month. We'll revert 595 May 23

**Comment by dkhamsing** [comment]
Still unsure about what to do with the funds - any more thoughts? @scribblemaniac @vpeschenkov

**Comment by vpeschenkov** [comment]
I don't have any thoughts. The buying of Apple Developer Membership looks good for me; however, I'm not sure how good it will be working in reality. Anyway, we can see, or we can save the money for a while.

**Comment by dkhamsing** [comment]
Not much progress here, I am thinking of sending @vpeschenkov $100 for all the help recently 😄

**Comment by dkhamsing** [comment]
It's not much, but I think he deserves it!!

**Comment by scribblemaniac** [comment]
I don't really have any further suggestions here. If that's what you want to do then go for it! I am glad to see him helping out so much 😁

**Comment by vpeschenkov** [comment]
Thank you, guys! I was happy to help 😄

**Comment by dkhamsing** [comment]
I’ll message you privately. Closing this but feel free to let me know if you have ideas 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
