### ISSUE TITLE
Interested in a gatsby site built from this data?

### ISSUE THREAD

**Issue by chmac** [dkhamsing/open-source-ios-apps#871]
There's some awesome data in here. Thanks for making this repo.

I'm wondering if there would be value in building a Gatsby static site version of this content. Maybe splitting the sections onto smaller pages, maybe adding a filter by license, potentially other enhancements. What do you think? Would it be useful to link to such a site from this repo? 

Wanted to get your feedback before starting to see if it's something you think would be helpful.

**Comment by dkhamsing** [comment]
@chmac thanks for your interest

Did you think of this as a separate project that would read from contents.json?

**Comment by chmac** [comment]
My first thought was to submit a PR that would add it to this repo. That way it'd be auto updated by netlify / GitHub actions / whatever is used to run the build process. We could potentially also use GitHub pages to host it. Would keep the whole thing tidily together. But I'm open to what you think makes sense.

I'm a big fan of open source, so anything we can do to make the discovery of open source apps easier seems like something worth putting a bit of effort into...

**Comment by dkhamsing** [comment]
Is there a way to use github-pages https://pages.github.com ? We had something for this project a long time ago but not sure it still works cc @scribblemaniac

**Comment by chmac** [comment]
@dkhamsing Yeah, in theory that would totally work. We just need to run the build somewhere, then push the results into the `gh-pages` branch I believe. But there's lots of code to automate all of that already. I'm happy to look into it a bit and make some suggestions of what would work if you think it's an idea worth pursuing.

**Comment by scribblemaniac** [comment]
Chiming in here. There was a small error in [the original website](http://dkhamsing.github.io/open-source-ios-apps/) which I have fixed so it can be seen as it was intended now. There's certainly a lot of room for improvement (see #400 for a rough idea) but it is functional and still holding up surprisingly well. I don't know enough to comment on whether or not GatsbyJS would be a good option to use. Personally I don't think it's worth a rewrite, but nobody has done anything with it since I stopped working on it either.

One thing to consider is that with the approach I took is that the contents.json is loaded dynamically, whereas it sounds like you want to load and process it during the build process. The advantage with my approach is that it does not require any automation or rebuilding and it is possible to do some things you wouldn't be able to do otherwise such as refresh the data without reloading the page or view the page with older data (neither implemented yet though). The alternate approach would have the advantage that it could theoretically optimize the web pages better for faster loading and would be definitely be better if you want to break it up into separate webpages because the full data would not have to be loaded each time.

**Comment by chmac** [comment]
@scribblemaniac OK, the existing site is pretty good already. @dkhamsing would you be open to linking to it from the GitHub repo description? I wouldn't have thought to look for it.

I'd favour the Gatsby route, building on every update, as I think the build time happens far less often than the runtime. So best do all the work ahead of time, once, and then less work later. But that's a whole other discussion!

@scribblemaniac Are you interested in developing the web version any further?

I'm pretty familiar with Gatsby, and having the data in a json file makes life super easy, so maybe I'll put some hours into it if I get the inspiration. I think having the current version linked from the repo would get to 80% of what I had in mind. I can see potential to add search, and other stuff, but that all seems like small optimisations of something that's already pretty good!

**Comment by dkhamsing** [comment]
@chmac 
Yes will add a link to the website, will report when done.

**Comment by dkhamsing** [comment]
Link to website added
![B6035C26-3AF4-4E75-A5F6-CE56304F6988](https://user-images.githubusercontent.com/4723115/89104760-85d1d100-d3d0-11ea-82f9-5c2d82b2b4bf.jpeg)
